#!/bin/bash

hostname=root@thezetaorbital.com

rm dist.tar.gz
yarn build
tar -cvvf dist.tar dist/*
gzip dist.tar
ssh $hostname 'rm -rf /srv/www/thezetaorbital.com/public_html/*'
scp dist.tar.gz $hostname:/srv/www/thezetaorbital.com/public_html/
ssh $hostname 'cd /srv/www/thezetaorbital.com/public_html; tar -zxvf dist.tar.gz; rm dist.tar.gz; mv dist/* .; rmdir dist;'
rm dist.tar.gz
scp -rd static/* $hostname:/srv/www/thezetaorbital.com/public_html/
ssh $hostname 'chown -R nginx /srv/www/thezetaorbital.com/'
ssh $hostname 'chgrp -R nginx /srv/www/thezetaorbital.com/'
